### ISSUE TITLE
Article Topic - data engineering

### ISSUE THREAD

**Issue by Marvel-D** [The-Complete-Hub/writers-guide#6]
## Proposed article introduction
 Getting into the field of data engineering, it is of great importance that you possess basic yet conceptual knowledge of the field as this would provide you with a solid foundation to develop further.
In this article, You will understand the steps in which data flows within an organization, who are data engineers, and their responsibilities.

## key takeaways: 
 The reader should be able to understand the data workflow in an organization, Who a data engineer is and the responsibilities associated with data engineers

References:
None

**Comment by Favour-dgreat** [comment]
Great. Please proceed with your article
