### ISSUE TITLE
Article Topic - Understanding Big Data

### ISSUE THREAD

**Issue by Marvel-D** [The-Complete-Hub/writers-guide#9]
## Writing sample:
[Introduction to data engineering](https://www.thecompletehub.com/blog/introduction%20to%20data%20engineering)

## Proposed title of the article: 
Understanding Big Data

## Proposed article introduction: 
Data is a term referring to facts and statistics collected together for reference or analytical purposes.
In this digital world, everyone leaves a digital footprint. Be it through lifestyle documentation, entertainment media, content creation or even posts on social media, the number of internet-connected devices we interact with daily record vast amounts of data about us and our environment.
This "vast amount of data" has been tagged **Big Data**.

## Key takeaways: 
- A basic understanding of big data
- The characteristics of big data and their effects on an industry
- The benefits and applications of big data
- The current challenges and limitations faced by big data professionals and industries

**Comment by Favour-dgreat** [comment]
Great!. Please go ahead
